### ISSUE TITLE
Enable NTP sync

### ISSUE THREAD

**Issue by nkryuchkov** [skycoin/skybian#47]
**Feature description**

Enable NTP sync in image to have correct time on boards.

**Is your feature request related to a problem? Please describe.**
The Skywire logic relies on system time. If time is not correct, issues like https://github.com/SkycoinPro/skywire-services/issues/274 may appear.

**Describe the solution you'd like**
Enable NTP synchronization in image.

**Additional context**
@Asgaror noticed that time on his board mismatched by 1.5 days

**Possible implementation**
- [ ] Install NTP service
- [ ] Enable it

**Comment by some4** [comment]
I wrote this in an install script for testnet.

The manager syncs to a pool and the rest sync to manager. I stopped because I didn't know how to implement with the python imager.

Take a look [here](https://github.com/some4/skywire-install-bash/blob/master/install.sh) hopefully y'all can make something out of it

**Comment by jdknives** [comment]
Closed by #70
